// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksApi.Models;

#nullable disable

namespace ParksApi.Migrations
{
    [DbContext(typeof(ParksApiContext))]
    partial class ParksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParksApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("ParkTypeId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.HasKey("ParkId");

                    b.HasIndex("ParkTypeId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            City = "Grand Canyon National Park",
                            Name = "Grand Canyon",
                            ParkTypeId = 1,
                            State = "AZ"
                        },
                        new
                        {
                            ParkId = 2,
                            City = "Yosemite National Park",
                            Name = "Yosemite",
                            ParkTypeId = 1,
                            State = "CA"
                        },
                        new
                        {
                            ParkId = 3,
                            City = "Acadia National Park",
                            Name = "Acadia",
                            ParkTypeId = 1,
                            State = "ME"
                        },
                        new
                        {
                            ParkId = 4,
                            City = "Big Sur",
                            Name = "Pfieffer Big Sur",
                            ParkTypeId = 2,
                            State = "CA"
                        },
                        new
                        {
                            ParkId = 5,
                            City = "Big Sur",
                            Name = "Julia Pfieffer Burns",
                            ParkTypeId = 2,
                            State = "CA"
                        },
                        new
                        {
                            ParkId = 6,
                            City = "Big Sur",
                            Name = "Andrew Molera",
                            ParkTypeId = 2,
                            State = "CA"
                        });
                });

            modelBuilder.Entity("ParksApi.Models.ParkType", b =>
                {
                    b.Property<int>("ParkTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("ParkTypeId");

                    b.ToTable("ParkType");

                    b.HasData(
                        new
                        {
                            ParkTypeId = 1,
                            Type = "National"
                        },
                        new
                        {
                            ParkTypeId = 2,
                            Type = "State"
                        });
                });

            modelBuilder.Entity("ParksApi.Models.Park", b =>
                {
                    b.HasOne("ParksApi.Models.ParkType", "Type")
                        .WithMany("Parks")
                        .HasForeignKey("ParkTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ParksApi.Models.ParkType", b =>
                {
                    b.Navigation("Parks");
                });
#pragma warning restore 612, 618
        }
    }
}
